**->Pandas Excersice**

**1.Read dataset cars_data.csv**

In [2]:
import pandas as pd
import numpy as np

In [3]:
#Read dataset cars_data.csv
df=pd.read_csv('Cars_data.csv')
df

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

**2.Print the columns names of the dataset**

In [4]:
#Print the columns names of the dataset
for x in df.columns:
    print(x)

index
company
body-style
wheel-base
length
engine-type
num-of-cylinders
horsepower
average-mileage
price

**3.Print no. of columns and rows in this dataset**

In [5]:
#Print no. of columns and rows in this dataset
print(df.shape)
print("No. of rows:",len(df))
print("No. of columns:",len(df.columns))

(61, 10)
No. of rows: 61
No. of columns: 10

**4.Find out if there are any NULL or blank values?**

In [94]:
#Find out if there are any NULL or blank values?
print(df.isnull())
print(df.isnull().values.any())  #retutrns TRUE if there are any null values

    index  company  body-style  wheel-base  length  engine-type  \
0   False    False       False       False   False        False
1   False    False       False       False   False        False
2   False    False       False       False   False        False
3   False    False       False       False   False        False
4   False    False       False       False   False        False
..    ...      ...         ...         ...     ...          ...
56  False    False       False       False   False        False
57  False    False       False       False   False        False
58  False    False       False       False   False        False
59  False    False       False       False   False        False
60  False    False       False       False   False        False

    num-of-cylinders  horsepower  average-mileage  price
0              False       False            False  False
1              False       False            False  False
2              False       False            False  False
3              False       False            False  False
4              False       False            False  False
..               ...         ...              ...    ...
56             False       False            False  False
57             False       False            False  False
58             False       False            False  False
59             False       False            False  False
60             False       False            False  False

[61 rows x 10 columns]
True

**5.Find out which column has how many NULL value?**

In [76]:
#Find out which column has how many NULL values
print(df.isnull().sum())

index               0
company             0
body-style          0
wheel-base          0
length              0
engine-type         0
num-of-cylinders    0
horsepower          0
average-mileage     0
price               3
dtype: int64

**6.Change the names of column horsepower to hp**

In [80]:
#Change the names of column horsepower to hp
df.rename(columns={"horsepower":"hp"})

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,hp,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

**7.Which is the most expensive car**

In [86]:
#Which is the most expensive car
# print(df['company'][df['price'].max()])
e=pd.DataFrame(df[['company','price']][df.price==df['price'].max()])
e

          company    price
35  mercedes-benz  45400.0

**8.Using slicing create data frame of only Toyota Cars**

In [21]:
#Using slicing create data frame of only Toyota Cars
#df.loc[company]=='toyota'
# #df_t.reset_index(inplace = True) 
#df_t
carcomp=df.groupby('company')
df_t=carcomp.get_group('toyota')
df_t

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
48,66,toyota,hatchback,95.7,158.7,ohc,four,62,35,5348.0
49,67,toyota,hatchback,95.7,158.7,ohc,four,62,31,6338.0
50,68,toyota,hatchback,95.7,158.7,ohc,four,62,31,6488.0
51,69,toyota,wagon,95.7,169.7,ohc,four,62,31,6918.0
52,70,toyota,wagon,95.7,169.7,ohc,four,62,27,7898.0
53,71,toyota,wagon,95.7,169.7,ohc,four,62,27,8778.0
54,79,toyota,wagon,104.5,187.8,dohc,six,156,19,15750.0

**9.Print count of total cars per company**

In [20]:
#Print count of total cars per company
cars=df.groupby('company').company.count()
print(cars)
#df['company'].value_counts()

company
alfa-romero      3
audi             4
bmw              6
chevrolet        3
dodge            2
honda            3
isuzu            3
jaguar           3
mazda            5
mercedes-benz    4
mitsubishi       4
nissan           5
porsche          3
toyota           7
volkswagen       4
volvo            2
Name: company, dtype: int64

--> The “group by” process: split-apply-combine

(1) Splitting the data into groups. (2). Applying a function(count,sum,mx,mn) to each group independently, (3) Combining the results into a data structure.

**10.Find each company’s highest price**

In [36]:
#Find each company’s highest price
print(df.groupby('company')['price'].max())
#print(df.groupby(['company','price']).max())

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

**11.Find each company’s lowest price**

In [37]:
#Find each company’s lowest price
print(df.groupby('company')['price'].min())

company
alfa-romero      13495.0
audi             13950.0
bmw              16430.0
chevrolet         5151.0
dodge             6229.0
honda             7295.0
isuzu             6785.0
jaguar           32250.0
mazda             5195.0
mercedes-benz    25552.0
mitsubishi        5389.0
nissan            6649.0
porsche          34028.0
toyota            5348.0
volkswagen        7775.0
volvo            12940.0
Name: price, dtype: float64

**12.Find average mileage of each car company**

In [78]:
#Find average mileage of each car company
m=df.groupby('company')
df_m=m['average-mileage'].mean()
df_m
#print(m['average-mileage'])
#av=df.groupby('company')[['company','average-mileage']]
#print(df.groupby(['company','average-mileage']))

company
alfa-romero      20.333333
audi             20.000000
bmw              19.000000
chevrolet        41.000000
dodge            31.000000
honda            26.333333
isuzu            33.333333
jaguar           14.333333
mazda            28.000000
mercedes-benz    18.000000
mitsubishi       29.500000
nissan           31.400000
porsche          17.000000
toyota           28.714286
volkswagen       31.750000
volvo            23.000000
Name: average-mileage, dtype: float64